# Generated by Django 5.1.7 on 2025-03-12 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url_scanner', '0001_initial'),
    ]

    operations = [
    ]
