# Generated by Django 5.1.7 on 2025-03-12 21:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhishingDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField(max_length=500)),
                ('api_key', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_frequency_hours', models.IntegerField(default=24)),
            ],
            options={
                'verbose_name': 'Phishing Database',
                'verbose_name_plural': 'Phishing Databases',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(blank=True, max_length=100, null=True)),
                ('job_title', models.CharField(blank=True, max_length=100, null=True)),
                ('api_key', models.CharField(blank=True, max_length=64, null=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('email_notifications', models.BooleanField(default=True)),
                ('enable_two_factor', models.BooleanField(default=False)),
                ('scan_history_days', models.IntegerField(default=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
