# Generated by Django 5.1.7 on 2025-03-12 21:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhishingIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_name', models.CharField(max_length=100)),
                ('indicator_type', models.CharField(choices=[('phrase', 'Urgent/Suspicious Phrase'), ('pattern', 'Text Pattern'), ('domain', 'Suspicious Domain'), ('attachment', 'Suspicious Attachment Type')], max_length=50)),
                ('pattern_value', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('severity', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Critical')], default=1)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Phishing Indicator',
                'verbose_name_plural': 'Phishing Indicators',
                'ordering': ['-severity', 'indicator_name'],
            },
        ),
        migrations.CreateModel(
            name='EmailAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_subject', models.CharField(max_length=500)),
                ('email_body', models.TextField()),
                ('email_sender', models.EmailField(max_length=255)),
                ('analysis_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_phishing', models.BooleanField(blank=True, null=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('has_suspicious_links', models.BooleanField(blank=True, null=True)),
                ('suspicious_links', models.TextField(blank=True, null=True)),
                ('has_urgent_language', models.BooleanField(blank=True, null=True)),
                ('urgent_phrases', models.TextField(blank=True, null=True)),
                ('has_misspellings', models.BooleanField(blank=True, null=True)),
                ('misspelled_words', models.TextField(blank=True, null=True)),
                ('has_suspicious_attachments', models.BooleanField(blank=True, null=True)),
                ('suspicious_attachments', models.TextField(blank=True, null=True)),
                ('has_spoofed_sender', models.BooleanField(blank=True, null=True)),
                ('sender_in_blacklist', models.BooleanField(blank=True, null=True)),
                ('sender_in_whitelist', models.BooleanField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Analysis',
                'verbose_name_plural': 'Email Analyses',
                'ordering': ['-analysis_date'],
            },
        ),
    ]
